### ISSUE TITLE
migrate 명령어 실행 시 tsconfig.json 오류

### ISSUE THREAD

**Issue by ienground** [wisdomstar94/torytis#2]
안녕하세요! 0.0.37 버전에서 1.0.10으로 버전 업데이트 이후 migrate 명령어를 실행하는 도중 생긴 오류입니다.
Readme 내용대로 (package.json 수정) 하고 나서 migrate를 해 보니 다음과 같은 로그가 뜹니다.
```
> torytis-tistory-skin-stroke@1.1.17 torytis
> torytis migrate

-> torytis 마이그레이션 시작!
-> 현재 torytis 버전 : "1.0.10"
?
thread 'main' panicked at src/sub_commands/c_migrate.rs:300:9:
tsconfig.json 에 "include" 가 선언되어 있지 않습니다. 선언 후에 다시 시도해주세요.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

tsconfig.json에 어떤 내용을 기입해야 되는지 궁금합니다 :)

**Comment by wisdomstar94** [comment]
안녕하세요. 아래와 같이 빈 배열인 "include" 를 추가 작성해주신 후 다시 migrate 명령어를 진행해주시면 됩니다! <br />

-- tsconfig.json
```
{
    ...
    "include": [
    ]
    ...
}
```

또한 torytis 는 vscode 에 최적화되어 있으며, `npm run torytis -- migrate` 또는 `npm run build:variable` 명령어 등을 통해 ts 파일이 새로 생겼다면 인식이 제대로 되지 않을 수 있으므로 vscode 를 종료 후 다시 시작 하시거나 ts server 를 restart 하시는 것을 추천드립니다.
